name: DMTV

on:
  schedule:
    - cron: '44 */4 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: config
        run: |
          git config --global user.email "<>"
          git config --global user.name "DMTV bot"
      
      - name: grab m3u files
        run: |
          cd iptv/dm  # Naviguer vers le bon répertoire où se trouve dmtv.py
          python3 dmtv.py  # Exécuter le script

      - name: git add
        run: |
          git add -A
          ls -la
          
      - name: commit & push
        run: |
          git pull
          git commit -m "dmtv updated"
          git push
