name: France 5

on:
  schedule:
    - cron: '08 */3 * * *'
  
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
      - uses: actions/checkout@v4

      - name: config
        run: |
          git config --global user.email "<>"
          git config --global user.name "d32k18"
      
      - name: Update France_5
        run: python3 dm/France_5.py > dm/France_5.m3u8
        
      - name: git add
        run: |
          git add -A
          ls -la 
          
      - name: commit & push
        run: |
          git pull origin main
          git commit -m "Update" -m "France 5"
          git push origin main
